### ISSUE TITLE
not work, need update offsets

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#55] opened 2023-12-14 07:41 UTC
use dev version

**Comment by himenekocn** [comment] 2023-12-14 07:43
"Teleport"
           {
                "windows"   "149"
                "linux"     "148"
            }
	   "IsEntityPawn"
            {
                "windows"   "153"
                "linux"     "152"
            }
	   "IsEntityController"
            {
                "windows"   "154"
                "linux"     "153"
            }

**Comment by himenekocn** [comment] 2023-12-14 07:44
"CollisionRulesChanged"
            {
                "windows"   "174"
                "linux"     "173"
            }

**Comment by GameChaos** [comment] 2023-12-14 08:42
duplicate of #54

**Closed by GameChaos** 2023-12-14 08:42 UTC
